// <auto-generated />
namespace Proverb.Data.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddSagacityToSage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSagacityToSage));
        
        string IMigrationMetadata.Id
        {
            get { return "201408121401253_AddSagacityToSage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
